# Generated by Django 5.2.5 on 2025-08-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='6E5169DBC9', max_length=10, unique=True),
        ),
    ]
